### ISSUE TITLE
Feet left todo

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/R2D2#5]
Outer Legs
- [x] Finish printing feet
- [x] Finish painting silver details
- [x] Finish printing silver details
- [ ] Finish glueing detail to each leg

Central Leg
- [x] Finish printing foot
- [ ] glue detail to central foot
