### ISSUE TITLE
Body todo

### ISSUE THREAD

**Issue by samsmithnz** [samsmithnz/R2D2#6]
- [ ] Use pegs to have main body tight and strong
- [ ] Glue together main body
- [ ] Glue together big doors
- [ ] Mount big doors
- [ ] Mount panel door
- [ ] Mount small panel door
- [ ] glue together big back door. 
- [ ] mount big back door
